version: '1.0'
services:
  jupyter-lab:
    build: ./TensorFlowFolder
    ports:
      - "8888:8888"
    volumes:
      - ./TensorFlowFolder:/tf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]